version: '2'
services:
 discovery-service:
  image: discovery-service:latest
  restart: always
  ports:
   - "8761:8761"
  logging:
   options:
    max-size: "10m"
 config-server:
  image: config-server:latest
  restart: always
  ports: 
   - "8888:8888"
  logging:
   options:
    max-size: "10m"
  links:
   - discovery-service
 api-gateway:
  image: api-gateway:latest
  ports:
   - "8080:8080"
  logging:
   options:
    max-size: "10m"
  links:
   - discovery-service
