version: '2'
services:
 config-server:
  image: config-server:latest
  restart: always
  ports: 
   - "8888:8888"
  logging:
   options:
    max-size: "10m"
 discovery-service:
  image: discovery-service:latest
  restart: always
  ports:
   - "8761:8761"
  logging:
   options:
    max-size: "10m"