eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 120000